import type {EventSubmissionCopy} from './eventSubmission'

export const eventSubmissionNB = {
  metaTitle: 'Send inn et arrangement | nepali.no',
  metaDescription: 'Send inn et arrangement for det nepalske miljøet i Norge til redaksjonell vurdering hos nepali.no.',
  eyebrow: 'Delta i fellesskapet', title: 'Send inn et arrangement',
  introduction: 'Send oss informasjon om et arrangement i organisasjonen eller fellesskapet. nepali.no vurderer informasjonen før eventuell publisering.',
  beforeYouBeginTitle: 'Før du begynner',
  beforeYouBeginItems: ['Ha korrekt og oppdatert arrangementsinformasjon klar.', 'Innsending innebærer ikke garanti for publisering.', 'Private kontaktopplysninger brukes bare til vurdering og nødvendig oppfølging.'],
  requiredNotice: 'Felt merket med stjerne (*) er obligatoriske.',
  privateNotice: 'Kontaktinformasjonen holdes privat og brukes bare av nepali.no sitt vurderingsteam.',
  publicContactNotice: 'Opplysninger her kan bare brukes på den offentlige arrangementssiden når du har gitt tillatelse.',
  sections: {language: 'Språk og publiseringsønske', organizer: 'Privat arrangørkontakt', publicContact: 'Foreslått offentlig arrangørinformasjon', event: 'Arrangementsinformasjon', location: 'Dato, sted eller nettilgang', registration: 'Påmelding og pris', image: 'Valgfritt bildeforslag', declarations: 'Bekreftelser og samtykke'},
  fields: {
    formInterfaceLanguage: 'Språk i skjemaet', submissionLanguage: 'Språk brukt i innsendingen', otherSubmissionLanguage: 'Oppgi annet språk', requestedPublicLanguage: 'Ønsket språk på offentlig side', organizerName: 'Navn på arrangør, organisasjon eller gruppe', privateContactName: 'Navn på kontaktperson', privateContactEmail: 'Privat e-postadresse', privateContactPhone: 'Privat telefonnummer', preferredContactLanguage: 'Foretrukket kontaktspråk', otherPreferredContactLanguage: 'Annet kontaktspråk',
    publicOrganizerName: 'Offentlig arrangørnavn', publicOrganizerUrl: 'Offentlig nettsted eller side', publicOrganizerEmail: 'Offentlig e-postadresse', publicOrganizerPhone: 'Offentlig telefonnummer', publicContactPermission: 'Jeg tillater publisering av de foreslåtte offentlige kontaktopplysningene', proposedTitle: 'Tittel på arrangementet', summary: 'Kort sammendrag', descriptionPlainText: 'Full arrangementsbeskrivelse', eventLanguages: 'Språk på arrangementet', otherEventLanguage: 'Annet arrangementsspråk', eventType: 'Arrangementstype', eventFormat: 'Arrangementsformat', isAllDay: 'Heldagsarrangement',
    startDateTime: 'Startdato og -tid', endDateTime: 'Sluttdato og -tid', venueName: 'Navn på sted', address: 'Adresse', postalCode: 'Postnummer', city: 'Sted eller by', mapUrl: 'Kartlenke', onlinePlatform: 'Nettplattform', onlineInformationUrl: 'Lenke til nettilgang eller informasjon', accessibilityInformation: 'Tilgjengelighetsinformasjon', transportInformation: 'Transport- eller parkeringsinformasjon', intendedAudience: 'Målgruppe', sourceUrl: 'Opprinnelig arrangement eller offentlig kilde',
    registrationRequirement: 'Krav til påmelding', registrationStatus: 'Påmeldingsstatus', registrationUrl: 'Lenke til påmelding eller billetter', registrationDeadline: 'Påmeldingsfrist', isFree: 'Gratis arrangement', priceDescription: 'Prisbeskrivelse', proposedImageUrl: 'Lenke til foreslått bilde', imageAltSuggestion: 'Forslag til alternativ bildetekst', imageCredit: 'Bildekreditering', imagePermissionConfirmed: 'Jeg bekrefter at bildet kan brukes og publiseres',
    authorityConfirmed: 'Jeg har myndighet til å sende inn arrangementet', accuracyConfirmed: 'Opplysningene er korrekte etter beste evne', editingTranslationAccepted: 'Jeg godtar at nepali.no kan redigere eller oversette', publicationNotGuaranteedAccepted: 'Jeg forstår at innsending ikke garanterer publisering', privacyRetentionAccepted: 'Jeg godtar personvern- og oppbevaringsinformasjonen',
  },
  help: {
    submissionLanguage: 'Velg hovedspråket du bruker i arrangementsinformasjonen.', requestedPublicLanguage: 'Endelig språk og redaksjonell utforming avgjøres av nepali.no ut fra behov og kapasitet.', privateContact: 'Opplysningene vises ikke automatisk på en offentlig side.', publicContact: 'Oppgi bare informasjon publikum kan bruke for å kontakte arrangøren.', publicContactPermission: 'Tydelig tillatelse er obligatorisk hvis offentlig e-post eller telefon foreslås.', summary: 'Oppsummer det viktigste i 2–4 setninger.', descriptionPlainText: 'Ta med formål, program, tidsplan og praktisk informasjon for deltakere.', eventLanguages: 'Velg alle språk deltakerne vil bruke eller trenger å forstå.', onlineAccessRequirement: 'For arrangementer på nett eller i hybridformat må du oppgi minst én av disse: nettplattform eller offentlig informasjonslenke.', sourceUrl: 'Oppgi arrangørens offisielle arrangementsside hvis den finnes.', proposedImageUrl: 'Direkte opplasting er ikke tilgjengelig ennå. Bruk bare en offentlig tilgjengelig lenke.', imagePermissionConfirmed: 'Ikke foreslå bildet hvis rettighetene er uklare.', privacyRetentionAccepted: 'Opplysningene kan oppbevares så lenge det er nødvendig for vurdering, kontakt og dokumentasjon.',
  },
  options: {
    interfaceLanguages: {ne: 'Nepali', nb: 'Norsk', en: 'Engelsk'}, submissionLanguages: {ne: 'Nepali', nb: 'Norsk', en: 'Engelsk', other: 'Annet'}, publicLanguages: {ne: 'Nepali', nb: 'Norsk', both: 'Både nepali og norsk', editorialDecision: 'Ingen preferanse, redaksjonell vurdering'}, contactLanguages: {ne: 'Nepali', nb: 'Norsk', en: 'Engelsk', other: 'Annet'}, eventFormats: {inPerson: 'Fysisk', online: 'På nett', hybrid: 'Fysisk og på nett'},
  },
  actions: {submit: 'Send til vurdering', submitting: 'Sender…', returnToEvents: 'Tilbake til arrangementer', useNepali: 'नेपाली', useNorwegian: 'Norsk', useEnglish: 'English'},
  messages: {
    validationSummaryTitle: 'Kontroller noen opplysninger', validationSummaryBody: 'Rett feltene som er markert, og prøv igjen.', successTitle: 'Arrangementet er mottatt', successBody: 'Arrangementsforslaget er trygt mottatt for vurdering.', successReference: 'Referanse for innsendingen', publicationNotice: 'Mottatt forslag er ikke en garanti for publisering.', rateLimited: 'Det er gjort for mange forsøk på kort tid. Prøv igjen senere.', temporarilyUnavailable: 'Tjenesten for arrangementsinnsending er midlertidig utilgjengelig.', storageFailed: 'Arrangementet kunne ikke lagres. Prøv igjen senere.', networkFailed: 'Det oppstod et nettverksproblem. Kontroller tilkoblingen og prøv igjen.', unexpectedError: 'Det oppstod en uventet feil. Prøv igjen.',
  },
} as const satisfies EventSubmissionCopy
